name: dynamite
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  build: ^2.3.1
  built_value: ^8.4.3
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  json_annotation: ^4.7.0
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  nit_picking:
    git:
      url: https://github.com/stack11/dart_nit_picking
      ref: 0b2ee0d
