name: neon_workspace
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  commitlint_cli: ^0.7.1
  coverage: ^1.7.2
  fvm: ^3.0.14
  husky: ^0.1.7
  melos: ^5.1.0
  custom_lint: ^0.6.2
