name: Dart CI
on:
  pull_request:

concurrency:
  group: dart-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dart-ci:
    name: Dart CI
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Install dart
        uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3 # v1
      - name: Setup
        run: |
          ./tool/setup.sh
          # Remove any changes from the automatic formatting
          git checkout .

      #- name: Check formatting
      #  run: melos run format:check
      #- name: Lint code
      #  run: melos run analyze
      - name: Run tests
        run: melos test
      - name: Upload coverage
        run: melos exec --file-exists="coverage/lcov.info" --concurrency=1 melos test:upload_coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
